#include <gtest/gtest.h>

#include <boost/filesystem.hpp>
#include <iostream>
#include <fstream>

TEST(SequenceMatcherTest, testRatio) {
    std::string filename = std::string("/tmp/") + boost::filesystem::unique_path().string();

    // We assume an umask of 022
    std::ofstream outfile(filename);
    outfile << "Test file generated by meld" << std::endl;
    outfile.close();

    boost::filesystem::path p(filename);
    boost::filesystem::file_status s = status(p);

    // Check if the umask was set to 022
    EXPECT_EQ(0644, s.permissions());

    // Check if I understood boost::filesystem::perms properly
    EXPECT_EQ(0200, (s.permissions() & (boost::filesystem::perms::owner_write | boost::filesystem::perms::group_write | boost::filesystem::perms::others_write)));

    boost::filesystem::remove(filename);
}
